extends: "airbnb"
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 6
plugins:
  - "react"
env:
  mocha: true
  es6: true
rules:
  max-len: ["error", 120, 2, { # 120 max len, 2 tab width
    ignoreUrls: true,
    ignoreComments: false
  }]
  quotes: ["error", "double", "avoid-escape"]
  no-shadow: ["error", { allow: ["err"] }]
  eqeqeq: ["error", "always", {"null": "ignore"}]
  space-before-keywords: 0 # deprecated, replaced with 'keyword-spacing'
  space-after-keywords: 0 # deprecated, replaced with 'keyword-spacing'
  space-return-throw-case: 0 # deprecated, replaced with 'keyword-spacing'
  no-empty-label: 0 # deprecated, replaced with 'no-labels'
  keyword-spacing: [2, {
    before: true,
    after: true,
    overrides: {
      return: { after: true },
      throw: { after: true },
      case: { after: true }
    }
  }]
  no-labels: [2, { allowLoop: false, allowSwitch: false }]
  no-unused-vars: ["error", { "argsIgnorePattern": "next" }]
  no-param-reassign: 0 # TODO: Add back with exceptions when https://github.com/eslint/eslint/issues/6505 is resolved